import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import {
  ArrowLeft,
  FileText,
  PenTool,
  Sparkles,
  Layout,
  Image,
  Type,
  Eye,
  Save,
  Wand2
} from 'lucide-react';

interface PageLayout {
  id: string;
  name: string;
  description: string;
  preview: string;
  sections: string[];
}

const CreateContent = () => {
  const navigate = useNavigate();
  const [contentType, setContentType] = useState<'page' | 'blog'>('page');
  const [selectedLayout, setSelectedLayout] = useState<string>('');
  const [title, setTitle] = useState('');
  const [excerpt, setExcerpt] = useState('');
  const [content, setContent] = useState('');
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const pageLayouts: PageLayout[] = [
    {
      id: 'hero-centered',
      name: 'Hero Centered',
      description: 'Large centered hero section with call-to-action',
      preview: '🎯',
      sections: ['Hero', 'Features', 'CTA']
    },
    {
      id: 'hero-left',
      name: 'Hero Left Aligned',
      description: 'Hero content aligned to the left with image on right',
      preview: '📱',
      sections: ['Hero Split', 'Content', 'Gallery']
    },
    {
      id: 'two-column',
      name: 'Two Column Layout',
      description: 'Balanced two-column content layout',
      preview: '📊',
      sections: ['Header', 'Two Columns', 'Footer']
    },
    {
      id: 'four-corners',
      name: 'Four Corners',
      description: 'Grid layout with four main content areas',
      preview: '⬜',
      sections: ['Header', 'Four Grid', 'Contact']
    },
    {
      id: 'landing-page',
      name: 'Landing Page',
      description: 'Complete landing page with multiple sections',
      preview: '🚀',
      sections: ['Hero', 'Features', 'Testimonials', 'Pricing', 'CTA']
    },
    {
      id: 'portfolio',
      name: 'Portfolio',
      description: 'Showcase work and projects',
      preview: '🎨',
      sections: ['Introduction', 'Projects Grid', 'About', 'Contact']
    }
  ];

  const blogLayouts: PageLayout[] = [
    {
      id: 'standard-blog',
      name: 'Standard Blog',
      description: 'Traditional blog post layout',
      preview: '📝',
      sections: ['Header', 'Content', 'Related Posts']
    },
    {
      id: 'featured-image',
      name: 'Featured Image',
      description: 'Large featured image with content below',
      preview: '🖼️',
      sections: ['Featured Image', 'Title', 'Content', 'Author Bio']
    },
    {
      id: 'magazine-style',
      name: 'Magazine Style',
      description: 'Multi-column magazine layout',
      preview: '📰',
      sections: ['Large Header', 'Multi-column Content', 'Sidebar']
    },
    {
      id: 'minimal-blog',
      name: 'Minimal Blog',
      description: 'Clean, minimal blog post design',
      preview: '✨',
      sections: ['Simple Header', 'Clean Content', 'Minimal Footer']
    }
  ];

  const handleGenerateContent = async () => {
    if (!aiPrompt.trim()) return;
    
    setIsGenerating(true);
    try {
      // This would connect to an AI service
      // For now, we'll simulate content generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const generatedContent = `# Generated Content for "${aiPrompt}"

This is AI-generated content based on your prompt. Here's a structured approach to your topic:

## Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## Main Points
- Key point about ${aiPrompt}
- Supporting evidence and examples
- Practical applications and benefits

## Conclusion
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

*This content was generated by AI and should be reviewed and customized to fit your needs.*`;

      setContent(generatedContent);
      if (!title) {
        setTitle(aiPrompt.charAt(0).toUpperCase() + aiPrompt.slice(1));
      }
    } catch (error) {
      console.error('Error generating content:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = () => {
    // This would save to the database
    console.log('Saving content:', { contentType, selectedLayout, title, excerpt, content });
    // For now, navigate back to content list
    navigate('/dashboard/content');
  };

  const currentLayouts = contentType === 'page' ? pageLayouts : blogLayouts;

  return (
    <div className="space-y-6 fade-in">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link to="/dashboard/content">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-3xl font-bold">Create New Content</h1>
          <p className="text-muted-foreground">
            Create a new page or blog post with AI assistance
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Content Creation Form */}
        <div className="lg:col-span-2 space-y-6">
          {/* Content Type Selection */}
          <Card className="gradient-card border-0 shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Type className="h-5 w-5" />
                Content Type
              </CardTitle>
              <CardDescription>
                Choose what type of content you want to create
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Tabs value={contentType} onValueChange={(value) => setContentType(value as 'page' | 'blog')}>
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="page" className="flex items-center gap-2">
                    <FileText className="h-4 w-4" />
                    Page
                  </TabsTrigger>
                  <TabsTrigger value="blog" className="flex items-center gap-2">
                    <PenTool className="h-4 w-4" />
                    Blog Post
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </CardContent>
          </Card>

          {/* Layout Selection */}
          <Card className="gradient-card border-0 shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Layout className="h-5 w-5" />
                Choose Layout
              </CardTitle>
              <CardDescription>
                Select a layout template for your {contentType}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {currentLayouts.map((layout) => (
                  <div
                    key={layout.id}
                    className={`p-4 border rounded-lg cursor-pointer transition-all hover:shadow-md ${
                      selectedLayout === layout.id
                        ? 'border-primary bg-primary/5 shadow-md'
                        : 'border-border hover:border-primary/50'
                    }`}
                    onClick={() => setSelectedLayout(layout.id)}
                  >
                    <div className="flex items-center gap-3 mb-2">
                      <span className="text-2xl">{layout.preview}</span>
                      <div className="flex-1">
                        <h3 className="font-medium">{layout.name}</h3>
                        <p className="text-sm text-muted-foreground">{layout.description}</p>
                      </div>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2">
                      {layout.sections.map((section) => (
                        <Badge key={section} variant="secondary" className="text-xs">
                          {section}
                        </Badge>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Content Details */}
          <Card className="gradient-card border-0 shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <PenTool className="h-5 w-5" />
                Content Details
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="title">Title *</Label>
                <Input
                  id="title"
                  placeholder={`Enter ${contentType} title...`}
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                />
              </div>

              {contentType === 'blog' && (
                <div className="space-y-2">
                  <Label htmlFor="excerpt">Excerpt</Label>
                  <Textarea
                    id="excerpt"
                    placeholder="Brief description of your blog post..."
                    value={excerpt}
                    onChange={(e) => setExcerpt(e.target.value)}
                    rows={3}
                  />
                </div>
              )}

              <div className="space-y-2">
                <Label htmlFor="content">Content</Label>
                <Textarea
                  id="content"
                  placeholder="Start writing your content here..."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  rows={12}
                  className="font-mono text-sm"
                />
              </div>

              <div className="flex gap-2">
                <Button onClick={handleSave} disabled={!title || !selectedLayout}>
                  <Save className="mr-2 h-4 w-4" />
                  Save Draft
                </Button>
                <Button variant="outline">
                  <Eye className="mr-2 h-4 w-4" />
                  Preview
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* AI Assistant Panel */}
        <div className="space-y-6">
          <Card className="gradient-card border-0 shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                AI Content Generator
              </CardTitle>
              <CardDescription>
                Generate content ideas and text with AI
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="ai-prompt">What would you like to write about?</Label>
                <Textarea
                  id="ai-prompt"
                  placeholder="E.g., 'Benefits of sustainable living', 'How to start a small business', etc."
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  rows={4}
                />
              </div>

              <Button 
                onClick={handleGenerateContent} 
                disabled={!aiPrompt.trim() || isGenerating}
                className="w-full"
              >
                {isGenerating ? (
                  <>
                    <Wand2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Wand2 className="mr-2 h-4 w-4" />
                    Generate Content
                  </>
                )}
              </Button>

              <div className="space-y-2">
                <h4 className="font-medium text-sm">AI Tools</h4>
                <div className="grid grid-cols-1 gap-2">
                  <Button variant="outline" size="sm">
                    <Sparkles className="mr-2 h-3 w-3" />
                    Improve Writing
                  </Button>
                  <Button variant="outline" size="sm">
                    <Image className="mr-2 h-3 w-3" />
                    Generate Images
                  </Button>
                  <Button variant="outline" size="sm">
                    <Type className="mr-2 h-3 w-3" />
                    SEO Optimize
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Quick Tips */}
          <Card className="gradient-card border-0 shadow-lg">
            <CardHeader>
              <CardTitle className="text-lg">Writing Tips</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3 text-sm">
                <div>
                  <h4 className="font-medium">Good Titles</h4>
                  <p className="text-muted-foreground">Be specific, include keywords, keep under 60 characters</p>
                </div>
                <div>
                  <h4 className="font-medium">Content Structure</h4>
                  <p className="text-muted-foreground">Use headers, bullet points, and short paragraphs</p>
                </div>
                <div>
                  <h4 className="font-medium">SEO Best Practices</h4>
                  <p className="text-muted-foreground">Include relevant keywords naturally throughout</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default CreateContent;