-- This migration is no longer needed as we've moved from user_type to role
-- The role column and constraints are handled in the platform admin system migration
-- Keeping this as a no-op for migration history