/**
 * Type guards for validating LLM-generated content structures
 *
 * This module provides runtime type validation for data generated by LLMs.
 * These guards ensure that the generated JSON matches our expected TypeScript
 * types before we process or save the data.
 *
 * Type guards follow a consistent pattern:
 * 1. Check if value is an object
 * 2. Validate required properties exist and have correct types
 * 3. Optionally validate nested structures
 * 4. Return boolean type predicate
 */

import {
  type HeroSection,
  type AboutSection,
  type ValueItem,
  type ValuesSection,
  type FeatureItem,
  type FeaturesSection,
  type ServiceItem,
  type ServicesSection,
  type TeamMember,
  type TeamSection,
  type Testimonial,
  type TestimonialsSection,
  type ContactSection,
  type SiteBranding,
  type SeoMetadata,
  type GeneratedSiteData
} from '@/lib/types/site-generation-jobs';

/**
 * Helper: Check if value is a non-null object
 */
function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Helper: Check if object has all required keys
 *
 * @param obj - Object to check
 * @param keys - Array of required key names
 * @returns True if all keys exist on the object
 *
 * @example
 * ```typescript
 * hasRequiredKeys(data, ['title', 'description']) // true if both exist
 * ```
 */
export function hasRequiredKeys(obj: unknown, keys: string[]): boolean {
  if (!isObject(obj)) {
    return false;
  }

  return keys.every(key => key in obj);
}

/**
 * Helper: Check if value is a non-empty string
 */
function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

/**
 * Helper: Check if value is an array of strings
 */
function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every(item => typeof item === 'string');
}

/**
 * Type guard for HeroSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid HeroSection
 */
export function isHeroSection(data: unknown): data is HeroSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['headline', 'subheadline', 'cta_text']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.headline) &&
    isNonEmptyString(data.subheadline) &&
    isNonEmptyString(data.cta_text) &&
    (data.background_image === undefined || typeof data.background_image === 'string')
  );
}

/**
 * Type guard for AboutSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid AboutSection
 */
export function isAboutSection(data: unknown): data is AboutSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'content']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    isStringArray(data.content) &&
    data.content.length > 0 &&
    (data.mission === undefined || typeof data.mission === 'string') &&
    (data.vision === undefined || typeof data.vision === 'string')
  );
}

/**
 * Type guard for ValueItem
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid ValueItem
 */
export function isValueItem(data: unknown): data is ValueItem {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'description', 'icon']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    isNonEmptyString(data.description) &&
    isNonEmptyString(data.icon)
  );
}

/**
 * Type guard for ValuesSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid ValuesSection
 */
export function isValuesSection(data: unknown): data is ValuesSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'values']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    Array.isArray(data.values) &&
    data.values.length > 0 &&
    data.values.every(isValueItem)
  );
}

/**
 * Type guard for FeatureItem
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid FeatureItem
 */
export function isFeatureItem(data: unknown): data is FeatureItem {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'description', 'icon']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    isNonEmptyString(data.description) &&
    isNonEmptyString(data.icon)
  );
}

/**
 * Type guard for FeaturesSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid FeaturesSection
 */
export function isFeaturesSection(data: unknown): data is FeaturesSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'features']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    Array.isArray(data.features) &&
    data.features.length > 0 &&
    data.features.every(isFeatureItem)
  );
}

/**
 * Type guard for ServiceItem
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid ServiceItem
 */
export function isServiceItem(data: unknown): data is ServiceItem {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['name', 'description']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.name) &&
    isNonEmptyString(data.description) &&
    (data.price === undefined || typeof data.price === 'string') &&
    (data.duration === undefined || typeof data.duration === 'string')
  );
}

/**
 * Type guard for ServicesSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid ServicesSection
 */
export function isServicesSection(data: unknown): data is ServicesSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'services']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    Array.isArray(data.services) &&
    data.services.length > 0 &&
    data.services.every(isServiceItem)
  );
}

/**
 * Type guard for TeamMember
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid TeamMember
 */
export function isTeamMember(data: unknown): data is TeamMember {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['name', 'role', 'bio']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.name) &&
    isNonEmptyString(data.role) &&
    isNonEmptyString(data.bio) &&
    (data.image === undefined || typeof data.image === 'string')
  );
}

/**
 * Type guard for TeamSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid TeamSection
 */
export function isTeamSection(data: unknown): data is TeamSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'members']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    Array.isArray(data.members) &&
    data.members.length > 0 &&
    data.members.every(isTeamMember)
  );
}

/**
 * Type guard for Testimonial
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid Testimonial
 */
export function isTestimonial(data: unknown): data is Testimonial {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['name', 'content']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.name) &&
    isNonEmptyString(data.content) &&
    (data.role === undefined || typeof data.role === 'string') &&
    (data.rating === undefined || (typeof data.rating === 'number' && data.rating >= 1 && data.rating <= 5))
  );
}

/**
 * Type guard for TestimonialsSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid TestimonialsSection
 */
export function isTestimonialsSection(data: unknown): data is TestimonialsSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'testimonials']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    (data.subtitle === undefined || typeof data.subtitle === 'string') &&
    Array.isArray(data.testimonials) &&
    data.testimonials.length > 0 &&
    data.testimonials.every(isTestimonial)
  );
}

/**
 * Type guard for ContactSection
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid ContactSection
 */
export function isContactSection(data: unknown): data is ContactSection {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'email']);
  if (!required) {
    return false;
  }

  // Validate additionalInfo if present
  if (data.additionalInfo !== undefined) {
    if (!isObject(data.additionalInfo)) {
      return false;
    }
    // Check that all values are strings
    const additionalInfo = data.additionalInfo;
    for (const value of Object.values(additionalInfo)) {
      if (typeof value !== 'string') {
        return false;
      }
    }
  }

  return (
    isNonEmptyString(data.title) &&
    isNonEmptyString(data.email) &&
    (data.phone === undefined || typeof data.phone === 'string') &&
    (data.address === undefined || typeof data.address === 'string') &&
    (data.hours === undefined || typeof data.hours === 'string')
  );
}

/**
 * Type guard for SiteBranding
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid SiteBranding
 */
export function isSiteBranding(data: unknown): data is SiteBranding {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['primary_color']);
  if (!required) {
    return false;
  }

  // Simple hex color validation (format: #RRGGBB)
  const isHexColor = (value: unknown): boolean => {
    return typeof value === 'string' && /^#[0-9A-Fa-f]{6}$/.test(value);
  };

  return (
    isHexColor(data.primary_color) &&
    (data.secondary_color === undefined || isHexColor(data.secondary_color)) &&
    (data.accent_color === undefined || isHexColor(data.accent_color)) &&
    (data.logo_description === undefined || typeof data.logo_description === 'string') &&
    (data.font_family === undefined || typeof data.font_family === 'string')
  );
}

/**
 * Type guard for SeoMetadata
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid SeoMetadata
 */
export function isSeoMetadata(data: unknown): data is SeoMetadata {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, ['title', 'description']);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.title) &&
    isNonEmptyString(data.description) &&
    (data.keywords === undefined || isStringArray(data.keywords)) &&
    (data.og_image === undefined || typeof data.og_image === 'string')
  );
}

/**
 * Type guard for foundation data (from Phase 1)
 *
 * Foundation data includes: site_name, tagline, description, hero, branding, seo
 *
 * @param data - Unknown data to validate
 * @returns True if data is valid foundation data
 */
export function isFoundationData(
  data: unknown
): data is {
  site_name: string;
  tagline: string;
  description: string;
  hero: HeroSection;
  branding: SiteBranding;
  seo: SeoMetadata;
} {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, [
    'site_name',
    'tagline',
    'description',
    'hero',
    'branding',
    'seo'
  ]);
  if (!required) {
    return false;
  }

  return (
    isNonEmptyString(data.site_name) &&
    isNonEmptyString(data.tagline) &&
    isNonEmptyString(data.description) &&
    isHeroSection(data.hero) &&
    isSiteBranding(data.branding) &&
    isSeoMetadata(data.seo)
  );
}

/**
 * Type guard for complete GeneratedSiteData
 *
 * @param data - Unknown data to validate
 * @returns True if data is a valid GeneratedSiteData
 */
export function isGeneratedSiteData(data: unknown): data is GeneratedSiteData {
  if (!isObject(data)) {
    return false;
  }

  const required = hasRequiredKeys(data, [
    'site_name',
    'tagline',
    'description',
    'hero',
    'about',
    'contact',
    'branding',
    'seo'
  ]);
  if (!required) {
    return false;
  }

  // Validate metadata if present
  if (data.metadata !== undefined && !isObject(data.metadata)) {
    return false;
  }

  return (
    isNonEmptyString(data.site_name) &&
    isNonEmptyString(data.tagline) &&
    isNonEmptyString(data.description) &&
    isHeroSection(data.hero) &&
    isAboutSection(data.about) &&
    isContactSection(data.contact) &&
    isSiteBranding(data.branding) &&
    isSeoMetadata(data.seo) &&
    (data.values === undefined || isValuesSection(data.values)) &&
    (data.features === undefined || isFeaturesSection(data.features)) &&
    (data.services === undefined || isServicesSection(data.services)) &&
    (data.team === undefined || isTeamSection(data.team)) &&
    (data.testimonials === undefined || isTestimonialsSection(data.testimonials))
  );
}