// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qugtyeexxmvgbqcyhvlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Z3R5ZWV4eG12Z2JxY3lodmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mjg1MjQsImV4cCI6MjA2ODAwNDUyNH0.FlOToGaQeRfTSZ6Ec6EGdxZ0rciphozs2K669P-hzr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});